service: webpage  # This ensures the webpage has a unique subdomain like webpage.logint-platform.uc.r.appspot.com

runtime: nodejs20  # Or python39 or any other runtime suitable for your static site (if using a server-side language)

instance_class: F2

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: /(.*)

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
